### ISSUE TITLE
error loading component

### ISSUE THREAD

**Issue by guoyangrui** [LucidWorks/query-autofiltering-component#2]
Hi I've compiled the source and added the query-autofiltering-component-1.0.jar to solr lib. I'm currently running solr 5.3.1 version. However I got the following error when I added requestHandler and searchComponent to solrconfig.xml and the core was unable to start

org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: org/apache/solr/util/plugin/SolrCoreAware

What could have caused this problem?

Thanks,

Yangrui

**Comment by guoyangrui** [comment]
I've successfully compiled the script but it throws an error. I've put the synonyms-autofilter.txt under the /conf folder.

&lt;response&gt;
&lt;lst name=&quot;responseHeader&quot;&gt;
&lt;int name=&quot;status&quot;&gt;500&lt;/int&gt;
&lt;int name=&quot;QTime&quot;&gt;76347&lt;/int&gt;
&lt;lst name=&quot;params&quot;&gt;
&lt;str name=&quot;q&quot;&gt;Kate Winslet&lt;/str&gt;
&lt;/lst&gt;
&lt;/lst&gt;
&lt;lst name=&quot;error&quot;&gt;
&lt;str name=&quot;msg&quot;&gt;input.length must be &gt; 0 (got 0)&lt;/str&gt;
&lt;str name=&quot;trace&quot;&gt;
java.lang.IllegalArgumentException: input.length must be &gt; 0 (got 0) at org.apache.lucene.analysis.synonym.SynonymMap$Builder.add(SynonymMap.java:146) at org.apache.lucene.analysis.synonym.SynonymMap$Builder.add(SynonymMap.java:206) at org.apache.solr.handler.component.QueryAutoFilteringComponent.addTerm(QueryAutoFilteringComponent.java:663) at org.apache.solr.handler.component.QueryAutoFilteringComponent.buildFieldMap(QueryAutoFilteringComponent.java:625) at org.apache.solr.handler.component.QueryAutoFilteringComponent.prepare(QueryAutoFilteringComponent.java:213) at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:251) at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143) at org.apache.solr.core.SolrCore.execute(SolrCore.java:2068) at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:669) at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:462) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:214) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:179) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.eclipse.jetty.server.Server.handle(Server.java:499) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) at java.lang.Thread.run(Thread.java:745)
&lt;/str&gt;
&lt;int name=&quot;code&quot;&gt;500&lt;/int&gt;
&lt;/lst&gt;
&lt;/response&gt;
